# permissions for end users to view backupsessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: backupsession-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: formol
    app.kubernetes.io/part-of: formol
    app.kubernetes.io/managed-by: kustomize
  name: backupsession-viewer-role
rules:
- apiGroups:
  - formol.desmojim.fr
  resources:
  - backupsessions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - formol.desmojim.fr
  resources:
  - backupsessions/status
  verbs:
  - get
