# permissions for end users to view backupconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backupconfiguration-viewer-role
rules:
- apiGroups:
  - formol.desmojim.fr
  resources:
  - backupconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - formol.desmojim.fr
  resources:
  - backupconfigurations/status
  verbs:
  - get
