apiVersion: formol.desmojim.fr/v1alpha1
kind: BackupConfiguration
metadata:
  labels:
    app.kubernetes.io/name: backupconfiguration
    app.kubernetes.io/instance: backupconfiguration-sample
    app.kubernetes.io/part-of: formol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: formol
  name: backupconfiguration-sample
spec:
  # TODO(user): Add fields here
