apiVersion: formol.desmojim.fr/v1alpha1
kind: BackupSession
metadata:
  labels:
    app.kubernetes.io/name: backupsession
    app.kubernetes.io/instance: backupsession-sample
    app.kubernetes.io/part-of: formol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: formol
  name: backupsession-sample
spec:
  # TODO(user): Add fields here
