apiVersion: formol.desmojim.fr/v1alpha1
kind: BackupConfiguration
metadata:
  name: backupconf-nginx
spec:
  repository:
    name: repo-minio
  schedule: "*/5 * * * *"
  target:
    apiVersion: v1
    kind: Deployment
    name: nginx-deployment
  volumeMounts:
    - name: empty
      mountPath: /data
