apiVersion: formol.desmojim.fr/v1alpha1
kind: Repo
metadata:
  labels:
    app.kubernetes.io/name: repo
    app.kubernetes.io/instance: repo-sample
    app.kubernetes.io/part-of: formol
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: formol
  name: repo-sample
spec:
  # TODO(user): Add fields here
