apiVersion: formol.desmojim.fr/v1alpha1
kind: BackupConfiguration
metadata:
  name: backupconfiguration-sample
  namespace: default
spec:
  repository:
    name: local-backups
  task: task-backup-pv
  schedule: "*/5 * * * *"
