apiVersion: formol.desmojim.fr/v1alpha1
kind: Function
metadata:
  name: function-backup-pvc
  namespace: backup
spec:
  name: function-backup-pvc
  image: desmo999r/formolcli
  args:
    - backup
    - volume
